### PR TITLE
Buildings map redesign

### PR DESCRIPTION
**Pull request by iubeda**
- Added 3 new buildings to the project and at the scene.
- Tested the project and all seems to work fine

Related with #231 

image

### CODE REVIEW

**Comment by jesusleon1995** [comment]
Three buildings implemented correctly with their textures

captura de pantalla 2016-11-21 a las 1 06 28

**Review by jesusleon1995 — APPROVED** [review]
All correct, good job

**Comment by iubeda** [comment]
Yay! thx @jesusleon1995 

Close #231

**Comment by iubeda** [comment]
Merged!

**Pull request merged**
