### PR TITLE
Ublevel1 midhealth model and texture

### PR DESCRIPTION
**Pull request by pauortega**
Model of ub with mid health
Added as fbx, blend doesn't recognize textures
Doesn't generate extra .mat

edificiubmidlife

### CODE REVIEW

**Review by stefanlonn — DISMISSED** [review]
works and doesn't generate .mats

**Comment by sashadgt** [comment]
No lo subais por ahora porfa

**Comment by pauortega** [comment]
ok, aqui se queda

**Comment by sashadgt** [comment]
Y aparte os pedire cambio en modelo para tener 4 lados planos porfa para poder poner torretas , o que el tejado sea plano

**Comment by pauortega** [comment]
Vale, tomo nota

**Review by sashadgt — APPROVED** [review]
Aproved

**Pull request merged**
