### PR TITLE
Macba

### PR DESCRIPTION
**Pull request by jdomenmi7**
Issue #315

Model with textures with good scale and rotation

Model in blender: 
macba_blender

Model in Unity:
macba_unity

An image of the original building which the model is based: 
macba

### CODE REVIEW

**Comment by pauortega** [comment]
Material isn't applied. Might be a bit small

**Comment by pauortega** [comment]
capture

**Comment by jdomenmi7** [comment]
Thanks for the review @pauortega 
I scaled the model to make it larger and reaplied the texture,now it should look like this:
macba_unity

**Comment by jesusleon1995** [comment]
Now it seems all right!

captura de pantalla 2016-12-11 a las 19 32 15

**Review by jesusleon1995 — APPROVED** [review]

**Pull request merged**
