### PR TITLE
Redesign current map

### PR DESCRIPTION
**Pull request by iubeda**
- Added some city block to the map.
- The project seems to build&run ok.
- The task #198 is not ended yet but it is better to merge some of the changes at the scene now.

image

### CODE REVIEW

**Comment by quimix93** [comment]
Don't we want to build the towers there? I mean, we want the towers to be placed as close as the road as possible. Is it possible to put the buildings in the center of the sidewalks?

**Comment by iubeda** [comment]
I have left space near the main building to place the towers, in the grassy areas. Anyway, the design is open to changes

**Review by quimix93 — APPROVED** [review]
Everything correct.

**Comment by quimix93** [comment]
Let's merge this to include the grid too. I would like to talk about replacing some of the buildings for the next sprint though.

**Pull request merged**
