### PR TITLE
Improve & create some buildings 

### PR DESCRIPTION
**Pull request by iubeda**
Improved the old buildings.
Create a new one.
Deleted the old buldings from the scene and reorganization of the CityBlocks (related with #285)

image

### CODE REVIEW

**Review by quimix93 — COMMENTED** [review]
I'm looking at the scene right now and just see the 4 buildings on the top-left corner of the map. Is that right?

**Comment by iubeda** [comment]
Yes, in this issue i only pushed the new buildings, in #285 i will add all of them in the scene.

**Review by Solero93 — COMMENTED** [review]
Are the .mat configured so that they won't make a mess like in the beginning? Moreover... why are there 22585 lines changed in the LightCameraTestScene ??

**Comment by iubeda** [comment]
Yes they are and the changes at the Scene is because i deleted the old buildings

**Review by sashadgt — APPROVED** [review]
aceptado x fin

**Comment by iubeda** [comment]
Close #304

**Pull request merged**
